"""empty message

Revision ID: 1afd2d48f8bd
Revises: 297119a0ccbf
Create Date: 2020-01-19 20:21:00.755924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1afd2d48f8bd'
down_revision = '297119a0ccbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=200), nullable=True),
    sa.Column('authorid', sa.String(length=100), nullable=True),
    sa.Column('subletid', sa.Integer(), nullable=True),
    sa.Column('datecreated', sa.DateTime(), nullable=True),
    sa.Column('datemodified', sa.DateTime(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['authorid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sublets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creatorid', sa.String(length=100), nullable=True),
    sa.Column('datecreated', sa.DateTime(), nullable=True),
    sa.Column('datemodified', sa.DateTime(), nullable=True),
    sa.Column('avgrating', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('profileimg', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['creatorid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('replies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=200), nullable=True),
    sa.Column('reviewid', sa.Integer(), nullable=True),
    sa.Column('authorid', sa.String(length=100), nullable=True),
    sa.Column('datecreated', sa.DateTime(), nullable=True),
    sa.Column('datemodified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['authorid'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewid'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('replies')
    op.drop_table('sublets')
    op.drop_table('reviews')
    # ### end Alembic commands ###
