"""users table

Revision ID: 297119a0ccbf
Revises: 
Create Date: 2020-01-03 19:09:58.482571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '297119a0ccbf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('profileimg', sa.String(length=200), nullable=True),
    sa.Column('verifiedstu', sa.Boolean(), nullable=True),
    sa.Column('datecreated', sa.String(length=50), nullable=True),
    sa.Column('trustscore', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
