"""empty message

Revision ID: 99d9b5b3c9f4
Revises: a50020944535
Create Date: 2020-01-21 19:50:15.000799

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '99d9b5b3c9f4'
down_revision = 'a50020944535'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'anonymous',
               existing_type=mssql.BIT(),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('users', 'datecreated',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('users', 'verifiedstu',
               existing_type=mssql.BIT(),
               type_=sa.Boolean(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'verifiedstu',
               existing_type=sa.Boolean(),
               type_=mssql.BIT(),
               existing_nullable=True)
    op.alter_column('users', 'datecreated',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    op.alter_column('users', 'anonymous',
               existing_type=sa.Boolean(),
               type_=mssql.BIT(),
               existing_nullable=True)
    # ### end Alembic commands ###
