"""empty message

Revision ID: a50020944535
Revises: 1afd2d48f8bd
Create Date: 2020-01-21 19:47:43.184337

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'a50020944535'
down_revision = '1afd2d48f8bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('anonymous', sa.Boolean(), nullable=True))
    op.alter_column('users', 'verifiedstu',
               existing_type=mssql.BIT(),
               type_=sa.Boolean(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'verifiedstu',
               existing_type=sa.Boolean(),
               type_=mssql.BIT(),
               existing_nullable=True)
    op.drop_column('users', 'anonymous')
    # ### end Alembic commands ###
